services:
  db:
    image: postgres:16
    container_name: atlaswatch_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${SPRING_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - atlasNetwork

  redis:
    image: redis:8.0.6-alpine3.21
    container_name: project_redis
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    networks:
      - atlasNetwork

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atlaswatch_backend
    restart: always
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATABASE_PASSWORD}
      MAIL_HOST: ${MAIL_HOST}
      EMAIL: ${EMAIL}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EXPIRATION_TIME_FOR_REFRESH_TOKEN: 86400000
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      PUBLIC_KEY: ${PUBLIC_KEY}
      PRIVATE_KEY: ${PRIVATE_KEY}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      TMDB_API_TOKEN: ${TMDB_API_TOKEN}
    ports:
      - "8080:8080"
    networks:
      - atlasNetwork

  frontend:
    build:
      context: ./moviehub-frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8080
    container_name: atlaswatch_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - atlasNetwork

networks:
  atlasNetwork:
    driver: bridge

volumes:
  db_data:
  redis_data:
